version: '3'
services:
  nats:
     image: nats:2-alpine
     container_name: nats
     hostname: nats
     restart: unless-stopped
     ports:
        - "4222:4222"
        - "6222:6222"
        - "8222:8222"
  s3:
    image: minio/minio:RELEASE.2020-10-12T21-53-21Z
    container_name: s3
    hostname: s3
    restart: unless-stopped
    ports:
        - "9000:9000"
    environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
    command: ['server', '/data']